#!/bin/sh

uci set sim_switch.@sim[0].denied='1'
uci set sim_switch.@sim[0].data_limit='0'
uci set sim_switch.@sim[0].no_network='1'
uci set sim_switch.@sim[0].interval='30'
uci set sim_switch.@sim[0].on_signal='0'
uci set sim_switch.@sim[0].fail_flag='1'
uci set sim_switch.@sim[0].retry_count='3'
uci set sim_switch.@sim[0].roaming='0'
uci set sim_switch.@sim[0].sms_limit='0'
uci set sim_switch.@sim[0].sim_not_ready='1'
uci set sim_switch.@sim[0].enable_back='0'
uci set sim_switch.@sim[0].order='1'
uci set sim_switch.@sim[0].enabled='1'
uci set sim_switch.@sim[0].data_fail='1'

uci set sim_switch.@sim[1].denied='1'
uci set sim_switch.@sim[1].data_limit='0'
uci set sim_switch.@sim[1].no_network='1'
uci set sim_switch.@sim[1].interval='30'
uci set sim_switch.@sim[1].on_signal='0'
uci set sim_switch.@sim[1].fail_flag='1'
uci set sim_switch.@sim[1].retry_count='3'
uci set sim_switch.@sim[1].roaming='0'
uci set sim_switch.@sim[1].sms_limit='0'
uci set sim_switch.@sim[1].sim_not_ready='1'
uci set sim_switch.@sim[1].enable_back='0'
uci set sim_switch.@sim[1].order='2'
uci set sim_switch.@sim[1].enabled='1'
uci set sim_switch.@sim[1].data_fail='1'

uci commit sim_switch

exit 0
