#!/bin/sh

#MWAN3 Interface Changes
uci set mwan3.mob1s1a1.enabled='1'
uci set mwan3.mob1s2a1.enabled='1'
uci set mwan3.wan.enabled='1'

#To reduce switch time
uci set mwan3.@condition[0].timeout='1'
uci set mwan3.@condition[0].interval='1'
uci set mwan3.@condition[0].down='2'

uci set mwan3.@condition[1].timeout='1'
uci set mwan3.@condition[1].interval='1'
uci set mwan3.@condition[1].down='2'

uci set mwan3.@condition[2].timeout='1'
uci set mwan3.@condition[2].interval='1'
uci set mwan3.@condition[2].down='2'

uci commit mwan3

exit 0
