[ubi]
partition = rootfs
filename = /media/home/FIRMWARES1/RUTX11/sdk2/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/tmp/openwrt-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin

[ubi_1]
partition = rootfs_1
filename = /media/home/FIRMWARES1/RUTX11/sdk2/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/tmp/openwrt-ipq40xx-generic-teltonika_rutx-squashfs-sysupgrade.bin
primary = ubi

[u-boot]
partition = 0:APPSBL
filename = /media/home/FIRMWARES1/RUTX11/sdk2/bin/targets/ipq40xx/generic/openwrt-ipq40xx-u-boot-stripped.elf

[u-boot_1]
partition = 0:APPSBL_1
filename = /media/home/FIRMWARES1/RUTX11/sdk2/bin/targets/ipq40xx/generic/openwrt-ipq40xx-u-boot-stripped.elf
primary = u-boot
