config queue 'SQMCellular'
	option enabled '0'
	option script 'piece_of_cake.qos'
	option upload '2048'
	option download '1024'
	option interface 'qmimux0'
	option qdisc 'cake'

config queue 'SQMWan'
	option enabled '0'
	option script 'piece_of_cake.qos'
	option upload '1024'
	option download '1024'
	option interface 'eth1'
	option qdisc 'cake'

config queue 'SQMLan'
	option enabled '0'
	option script 'piece_of_cake.qos'
	option upload '1024'
	option download '1024'
	option interface 'br-lan'
	option qdisc 'cake'

config queue 'SQMWifi'
	option enabled '0'
	option script 'piece_of_cake.qos'
	option upload '1024'
	option download '1024'
	option interface 'br-wifi'
	option qdisc 'cake'
