local M = {}

M.STATUS_CODES = {
	CH_CHANGED = 1,
	DEV_NOT_FOUND = 2,
	DFS_CHANNEL_SCAN = 3,
	WIFI_NET_NOT_FOUND = 4,
	ONLY_ONE_STA = 5,
	SCAN_NOT_POSSIBLE = 6,
	STA_ACTION_COULD_NOT_PARSE = 7
}

M.WIFI_DRIVERS = {
	MAC80211 = "mac80211",
	RALINK = "ralink",
	QCAWIFI = "qcawifi"
}

M.CODES = {
	MAX_WIFI_IFACES = 1,
	MAX_STA_COUNT = 2,
	ONLY_SINGLE_MULTI_AP_ALLOWED = 3
}

M.LOCATION = {
	ANY = "0x20",
	OUTDOOR = "0x4f"
}

return M
