#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/cioClient
    procd_set_param respawn 3600 30 0
    procd_close_instance
}

stop_service() {
    echo "Stopping cioClient..."
    killall -9 cioClient 2>/dev/null
}

restart() {
    echo "Restarting cioClient..."
    stop_service
    echo "Waiting 5 seconds..."
    sleep 5
    start_service
}
