#!/bin/sh /etc/rc.common

START=05
STOP=90

start() {
	# Main banner
	cat << 'EOF' > /etc/banner
 _____ _     _     _____ ____ ___
| ____| |   | |   | ____/ ___/ _ \
|  _| | |   | |   |  _|| |  | | | |
| |___| |___| |___| |__| |__| |_| |
|_____|_____|_____|_____\____\___/
Elleco Networks ELC6400 Series 2026
EOF

	# Logo banner
	cat << 'EOF' > /etc/banner.logo
 _____ _     _     _____ ____ ___
| ____| |   | |   | ____/ ___/ _ \
|  _| | |   | |   |  _|| |  | | | |
| |___| |___| |___| |__| |__| |_| |
|_____|_____|_____|_____\____\___/
Elleco Networks ELC6400 Series 2026
EOF
}

