#!/usr/bin/lua

local open = io.open

local function read_file(path)
  local file = open(path, "rb")
  if not file then return nil end
  local content = file:read "*a"
  file:close()
  return content
end

local fileContent = read_file("/www/index.html.gz");
print("Content-Type: text/html\r")
print("Content-Encoding: gzip\r")
print("Status: 200 OK\r\n")
io.write(fileContent)
