/* eslint-disable cypress/unsafe-to-chain-command */
describe('Search functionality', () => {
  before(() => {
    localStorage.removeItem('recent-searches')
    cy.login()
    cy.hitPage('/status/overview')
  })
  after(() => {
    cy.logout()
  })
  it('searches for pages and visits them, then checks recents', () => {
    cy.get('div.search').click()
    cy.fillInput('search', 'system')
    cy.get('[test-id="search-result-0"]').click()
    cy.document().its('body').find('.spin-content')
    cy.document().its('body').find('.spin-content').should('not.exist')
    cy.url().should('include', '/status/system')
    cy.get('div.search').click()
    cy.fillInput('search', 'mobile')
    cy.get('[test-id="search-result-0"]').click()
    cy.document().its('body').find('.spin-content')
    cy.document().its('body').find('.spin-content').should('not.exist')
    cy.url().should('include', '/status/network/mobile')
    cy.get('div.search').click()
    cy.get('[test-id="search-result-0"]').contains('mobile')
  })
  it('searches with keyboard', () => {
    cy.get('body').type('/a').get('.box').should('be.visible')
    cy.fillInput('search', 'a').type('{downArrow}{downArrow}{downArrow}{downArrow}{downArrow}{downArrow}')
    cy.get('[test-id="search-result-6"]').should('be.visible').getInput('search').type('{Enter}')
    cy.document().its('body').find('.spin-content')
    cy.document().its('body').find('.spin-content').should('not.exist')
    cy.get('body').type('/a').get('.box').should('be.visible')
    cy.fillInput('search', 'a').type('{upArrow}')
    cy.get('[test-id="search-results"]').last().should('be.visible').getInput('search').type('{Enter}')
    cy.document().its('body').find('.spin-content')
    cy.document().its('body').find('.spin-content').should('not.exist')
    cy.get('body').type('/').get('.box').should('be.visible')
    cy.fillInput('search', 'test').type('{esc}')
    cy.get('.box').should('not.be.visible')
  })
  it('searches on mobile', () => {
    cy.viewport('iphone-6')
    cy.get('div.search').click()
    cy.fillInput('search', 'system')
    cy.get('[test-id="search-result-0"]').click()
    cy.document().its('body').find('.spin-content')
    cy.document().its('body').find('.spin-content').should('not.exist')
    cy.url().should('include', '/status/system')
    cy.get('div.search').click()
    cy.get('[test-id="search-result-0"]').contains('system')
    cy.get('div.search').click()
    cy.fillInput('search', 'system')
    cy.get('.close-btn').click()
    cy.get('.box').should('not.be.visible')
  })
})
