import createWrapper from '@tests/unit/mockFactory'
import InterfaceStatus from '@/components/shared/InterfaceStatus.vue'

describe('InterfaceStatus.vue', () => {
  let wrapper
  let wrapperOptions
  beforeEach(() => {
    wrapperOptions = {
      props: {
        status: {},
        modemList: [],
        dataLimit: [],
        simcards: [],
        wirelessNetworks: [],
        deviceStatus: []
      }
    }
    wrapper = createWrapper(InterfaceStatus, wrapperOptions)
  })

  it.each`
    status                                                                                                                         | wirelessNetworks        | deviceStatus                                     | dataLimit                                                | modemList                                                                     | simcards                                                   | expectedStatus
    ${undefined}                                                                                                                   | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'default'}
    ${{ enabled: false }}                                                                                                          | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'disabled'}
    ${{ enabled: true, is_up: false, network_type: 'mobile' }}                                                                     | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'disconnectedMobile'}
    ${{ enabled: true, is_up: false, network_type: 'wireless' }}                                                                   | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'disconnectedWireless'}
    ${{ enabled: true, is_up: false, network_type: 'wired' }}                                                                      | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'disconnectedEth'}
    ${{ enabled: true, is_up: true }}                                                                                              | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'up'}
    ${{ enabled: true, is_up: false, pending: true, proto: 'dhcp' }}                                                               | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'obtainingIPv4'}
    ${{ enabled: true, is_up: false, pending: true, proto: 'dhcpv6' }}                                                             | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'obtainingIPv6'}
    ${{ enabled: true, is_up: false, pending: true, proto: 'pppoe' }}                                                              | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'connectingPPPoe'}
    ${{ enabled: true, is_up: false, proto: 'static', errors: [{ code: 'NO_DEVICE' }] }}                                           | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'noDevice'}
    ${{ enabled: true, name: 'lan', is_up: false, proto: 'static', errors: [{ code: 'NO_DEVICE' }] }}                              | ${[{ network: 'lan' }]} | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'disconnectedWireless'}
    ${{ enabled: true, name: 'lan', is_up: false, device: 'br-lan' }}                                                              | ${[{ network: 'lan' }]} | ${[{ name: 'br-lan', up: true, carrier: true }]} | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'starting'}
    ${{ enabled: false, name: 'lan', is_up: true }}                                                                                | ${[{ network: 'lan' }]} | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${'stopping'}
    ${{ enabled: true, is_up: false, proto: 'pppoe', errors: [{ code: 'CONNECT_FAILED' }] }}                                       | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${{ help: 'If set, verify the "Service name" and "Access concentrator name" fields. Then, check the PPPoE server config and logs for any issues.', helpTitle: expect.any(String), status: 'Failed to find server', type: 'error' }}
    ${{ enabled: true, is_up: false, proto: 'pppoe', errors: [{ code: 'INVALID_ADDRESS' }] }}                                      | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${{ help: 'IP address is invalid', helpTitle: expect.any(String), status: 'Error', type: 'error' }}
    ${{ enabled: true, is_up: false, proto: 'pppoe', errors: [{ code: 'IDLE_TIMEOUT' }] }}                                         | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${{ help: 'Unexpected PPPoE error: IDLE_TIMEOUT (code: 12)', helpTitle: expect.any(String), status: 'Error', type: 'error' }}
    ${{ enabled: true, network_type: 'mobile', errors: [], is_up: false, up: true, id: 'mob1s1a1' }}                               | ${[]}                   | ${[]}                                            | ${[{ data_used: 100, data_limit: 100, id: 'mob1s1a1' }]} | ${[]}                                                                         | ${[]}                                                      | ${{ help: 'Mobile data limit reached', helpTitle: expect.any(String), status: 'Inactive', type: 'warning' }}
    ${{ enabled: true, network_type: 'mobile', errors: [], is_up: false, id: 'mob1s1a1', bringup: true }}                          | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[]}                                                                         | ${[]}                                                      | ${{ help: 'Mobile data is turned off by an external application', helpTitle: expect.any(String), status: 'Inactive', type: 'warning' }}
    ${{ enabled: true, network_type: 'mobile', errors: [], is_up: false, up: true, id: 'mob1s1a1', modem_id: 'modem1', sim: '1' }} | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[{ active_sim: 1, id: 'modem1', wwan_gnss_conflict: true, gnss_state: 1 }]} | ${[]}                                                      | ${{ help: 'Mobile data is not working because the GPS is on', helpTitle: expect.any(String), status: 'Inactive', type: 'warning' }}
    ${{ enabled: true, network_type: 'mobile', errors: [], is_up: false, up: true, id: 'mob1s1a1', modem_id: 'modem1', sim: '1' }} | ${[]}                   | ${[]}                                            | ${[]}                                                    | ${[{ active_sim: 1, id: 'modem1', operator_state: 'ROAMING' }]}               | ${[{ position: '1', modem: 'modem1', deny_roaming: '1' }]} | ${{ help: 'Mobile data is not allowed when roaming', helpTitle: expect.any(String), status: 'Inactive', type: 'warning' }}
  `('returns status $expectedStatus', async ({ status, config, dataLimit, wirelessNetworks, deviceStatus, modemList, simcards, expectedStatus }) => {
    await wrapper.setProps({ status, config, wirelessNetworks, dataLimit, modemList, simcards, deviceStatus })
    expect(typeof expectedStatus === 'string' ? wrapper.vm.statuses[expectedStatus] : expectedStatus).toEqual(
      Array.isArray(wrapper.vm.parsedStatus) ? wrapper.vm.parsedStatus[0] : wrapper.vm.parsedStatus
    )
  })
})
